__app_name__ = "ProxLB"
__app_desc__ = "An advanced resource scheduler and load balancer for Proxmox clusters."
__author__ = "Florian Paul Azim Hoberg <gyptazy>"
__copyright__ = "Copyright (C) 2025 Florian Paul Azim Hoberg (@gyptazy)"
__license__ = "GPL-3.0"
__version__ = "2.0.0"
__url__ = "https://github.com/credativ/ProxLB"
