name: Code linting
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.11
          - 3.12
          - 3.13
          - 3.14
    steps:
      - uses: actions/checkout@v3
      - name: Setup dependencies for code linting
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install additional dependencies for code linting
        run: |
          pip3 install poetry
      - name: Run code linting on ProxLB Python code
        run: |
          make test
